name: Main Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true # Включает встроенное кэширование NuGet
        cache-dependency-path: '**/packages.lock.json' # Или путь к решению

    - name: Restore dependencies
      run: dotnet restore BaseWebApplication/BaseWebApplication.sln

    - name: Build
      run: dotnet build --no-restore BaseWebApplication/BaseWebApplication.sln

    - name: Run All Tests
      # Можно запустить все тесты одной командой через файл решения, 
      # либо оставить список для точечного контроля
      run: |
        dotnet test --no-build --verbosity normal Template/Tests/Template.Tests/Template.Tests.csproj
        dotnet test --no-build --verbosity normal Comment/Tests/Comment.Tests/Comment.Tests.csproj
        dotnet test --no-build --verbosity normal Answer/tests/Answer.Domain.Tests/Answer.Domain.Tests.csproj
        dotnet test --no-build --verbosity normal Answer/tests/Answer.Infrastructure.Tests/Answer.Infrastructure.Tests.csproj
        dotnet test --no-build --verbosity normal Answer/tests/Answer.Api.IntegrationTests/Answer.Api.IntegrationTests.csproj
